discussions/urls.py
from django.conf.urls import url

from . import views

app_name = 'discussions'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>Q[0-9]+)$', views.question, name='question'),
    url(r'^ask/', views.ask, name='ask'),
    url(r'^answer/(?P<question_id>Q[0-9]+)$', views.answer, name='answer'),
    url(r'^delete/(?P<id>[AQ][0-9]+)', views.delete, name='delete'),
    url(r'^edit/(?P<id>[AQ][0-9]+)', views.edit, name='edit'),
    url(r'^confirm/(?P<id>[AQ][0-9]+)', views.confirm, name='confirm'),
    url(r'^vote/', views.vote, name='vote'),
]

main/urls.py
from django.conf.urls import url

from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/', views.login_view, name='login'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^search/', views.search, name='search'),
    url(r'^about/', views.about, name='about'),
    url(r'^leaderboard/', views.LeaderBoard, name='leaderboard'),
    url(r'^activity/', views.activity_all, name='activity_all'),
    url('^profile/(?P<username>[a-zA-Z0-9_]+)', views.profile, name='profile'),
    url('^activity/(?P<username>[a-zA-Z0-9_]+)', views.activity, name='activity'),
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    url(r'^posts/', views.posts, name='posts'),
    url(r'^post/(?P<id>P[0-9]+)', views.post, name='post'),

]

pf/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^',include('main.urls')),
    url(r'^discussions/',include('discussions.urls')),
    url(r'^admin/', admin.site.urls),
]

discussions/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User


# Create your models here.


class Question(models.Model):
    title = models.CharField(max_length=200, default="")
    description = models.CharField(max_length=1055, default="")
    date = models.DateTimeField(default=datetime.now, blank=True)
    username = models.ForeignKey(User, on_delete=None)
    votes = models.IntegerField(default=0)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Answer(models.Model):
    QID = models.ForeignKey(Question, on_delete=None)
    description = models.CharField(max_length=1055, default="")
    date = models.DateTimeField(default=datetime.now, blank=True)
    username = models.ForeignKey(User, on_delete=None)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.username.username


class Vote(models.Model):
    username = models.ForeignKey(User, on_delete=None)
    QID = models.ForeignKey(Question, on_delete=None, null=True, blank=True)
    AID = models.ForeignKey(Answer, on_delete=None, null=True, blank=True)
    vote = models.BooleanField(default=True)

    class Meta:
        ordering = ['-QID', '-AID']

    def __str__(self):
        if self.QID is not None:
            return str(self.QID.id) + '_' + self.username.username + '_' + str(self.vote)
        else:
            return str(self.AID.id) + '_' + self.username.username + '_' + str(self.vote)

discussions/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, reverse, get_object_or_404
from .form import QuestionForm, AnswerForm
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from .models import Question, Answer, Vote, User
from django.db.models import Q
from main.models import Profile, Activity
from difflib import SequenceMatcher
from main.form import Loginform


# Create your views here.

def similar(a, b):
    return SequenceMatcher(None, a, b).ratio()


def ask(request):
    return render(request, 'discussions/ask.html', {"form": QuestionForm()})


@login_required
def index(request):
    if request.method == "POST" and request.POST.get('title', None) and request.POST.get('description', None):
        question = Question.objects.create(title=request.POST["title"], description=request.POST["description"],
                                           username=User.objects.get(username=request.user.username))
        question.save()
        Activity.objects.create(by_username=User.objects.get(username=request.user.username), QID=question,
                                type=True).save()
        return HttpResponseRedirect(reverse('discussions:question', kwargs={'question_id': "Q" + str(question.id)}))
    return render(request, 'discussions/discussion.html',
                  {"questions": Question.objects.all(), "activities": Activity.objects.all()[:10]})


@login_required
def question(request, question_id):
    question_id = int(question_id[1:])
    question = get_object_or_404(Question, id=question_id)
    questions = Question.objects.all()
    related = []
    answers = Answer.objects.filter(QID=question)
    for q in questions:
        score = (similar(q.title, question.title))
        if score > 0.3 and score != 1:
            related.append(q)
    votes = Vote.objects.filter(username=User.objects.get(username=request.user.username)).filter(
        Q(QID=question_id) | Q(AID__in=Answer.objects.filter(QID=question_id).values_list('id', flat=True)))
    return render(request, 'discussions/question.html',
                  {"question": question, "votes": votes, "related": related, "answers": answers,
                   "activities": Activity.objects.all()[:7], "form": AnswerForm()})


@login_required
def answer(request, question_id):
    question_id = int(question_id[1:])
    question = get_object_or_404(Question, id=question_id)
    if request.method == "POST" and request.POST.get('description', None):
        user = User.objects.get(username=request.user.username)
        profile = Profile.objects.get(username=user)
        answer = Answer.objects.create(QID=question,
                                       description=request.POST['description'],
                                       username=user)
        profile.points += 2
        profile.save()
        answer.save()
        question.count += 1
        question.save()
        Activity.objects.create(by_username=User.objects.get(username=request.user.username), type=True, QID=question,
                                AID=answer).save()
    return HttpResponseRedirect(reverse('discussions:question', kwargs={'question_id': "Q" + str(question.id)}))


def vote(request):
    id = request.GET.get('id', None)
    type = request.GET.get('type', None)
    if id[0] == 'Q':
        id = id[1:]
        question = Question.objects.get(id=id)
        user = Profile.objects.get(username=User.objects.get(username=question.username))
        if int(type) == 1:
            question.votes += 1
            user.points += 1
            vote = Vote.objects.filter(username=User.objects.get(username=request.user.username), QID=question,
                                       vote=False)
            Activity.objects.create(by_username=User.objects.get(username=request.user.username), QID=question,
                                    on_username=User.objects.get(username=question.username), vote=True).save()
            if vote.exists():
                vote.delete()
            else:
                Vote.objects.create(username=User.objects.get(username=request.user.username), QID=question, vote=True)
        else:
            question.votes -= 1
            user.points -= 1
            vote = Vote.objects.filter(username=User.objects.get(username=request.user.username), QID=question,
                                       vote=True)
            Activity.objects.create(by_username=User.objects.get(username=request.user.username), QID=question,
                                    on_username=User.objects.get(username=question.username), vote=False).save()
            if vote.exists():
                vote.delete()
            else:
                Vote.objects.create(username=User.objects.get(username=request.user.username), QID=question, vote=False)
        user.save()
        question.save()
    else:
        id = id[1:]
        print(id)
        answer = Answer.objects.get(id=id)
        user = Profile.objects.get(username=User.objects.get(username=answer.username))
        if int(type) == 1:
            answer.votes += 1
            user.points += 1
            vote = Vote.objects.filter(username=User.objects.get(username=request.user.username), AID=answer,
                                       vote=False)
            Activity.objects.create(by_username=User.objects.get(username=request.user.username), AID=answer,
                                    QID=Question.objects.get(id=answer.QID.id),
                                    on_username=User.objects.get(username=answer.username), vote=True).save()
            if vote.exists():
                vote.delete()
            else:
                Vote.objects.create(username=User.objects.get(username=request.user.username), AID=answer, vote=True)
        else:
            answer.votes -= 1
            user.points -= 1
            vote = Vote.objects.filter(username=User.objects.get(username=request.user.username), AID=answer, vote=True)
            Activity.objects.create(by_username=User.objects.get(username=request.user.username), AID=answer,
                                    QID=Question.objects.get(id=answer.QID.id),
                                    on_username=User.objects.get(username=answer.username), vote=False).save()
            if vote.exists():
                vote.delete()
            else:
                Vote.objects.create(username=User.objects.get(username=request.user.username), AID=answer, vote=False)
        answer.save()
        user.save()
    return JsonResponse({})


@login_required
def delete(request, id):
    if id[0] == 'Q':
        id = id[1:]
        question = get_object_or_404(Question, id=id)
        if question.username == request.user:
            return render(request, 'discussions/delete.html', {"question": question})
        else:
            return HttpResponseRedirect(reverse('discussions:question', kwargs={'question_id': id}))
    else:
        id = id[1:]
        answer = get_object_or_404(Answer, id=id)
        if answer.username == request.user:
            return render(request, 'discussions/delete.html', {"answer": answer})
        else:
            return HttpResponseRedirect(reverse('discussions:question', kwargs={'question_id': answer.QID.QID}))


@login_required
def confirm(request, id):
    if id[0] == 'Q':
        id = id[1:]
        question = get_object_or_404(Question, id=id)
        if question.username == request.user:
            question.delete()
            return HttpResponseRedirect(reverse('discussions:index'))
        else:
            return HttpResponseRedirect(reverse('discussions:question', kwargs={'question_id': id}))
    else:
        id = id[1:]
        answer = get_object_or_404(Answer, id=id)
        if answer.username == request.user:
            temp_id = "Q" + str(answer.QID.id)
            answer.delete()
            return HttpResponseRedirect(reverse('discussions:question', kwargs={'question_id': temp_id}))
        else:
            return HttpResponseRedirect(reverse('discussions:question', kwargs={'question_id': answer.QID.id}))


@login_required
def edit(request, id):
    if request.method == "POST" and request.POST.get('description'):
        if id[0] == 'Q':
            id = id[1:]
            question = get_object_or_404(Question, id=id)
            question.title = request.POST.get('title')
            question.description = request.POST.get('description')
            question.save()
            return HttpResponseRedirect(reverse('discussions:question', kwargs={'question_id': "Q" + str(id)}))
        else:
            id = id[1:]
            answer = get_object_or_404(Answer, id=id)
            answer.description = request.POST.get('description')
            answer.save()
            return HttpResponseRedirect(
                reverse('discussions:question', kwargs={'question_id': "Q" + str(answer.QID.id)}))
    else:
        if id[0] == 'Q':
            id = id[1:]
            question = get_object_or_404(Question, id=id)
            if question.username == request.user:
                return render(request, 'discussions/ask.html',
                              {"form": QuestionForm(instance=question), "question": question})
            else:
                return HttpResponseRedirect(reverse('discussions:question', kwargs={'question_id': "Q" + str(id)}))
        else:
            id = id[1:]
            answer = get_object_or_404(Answer, id=id)
            if answer.username == request.user:
                return render(request, 'discussions/ask.html',
                              {"form": QuestionForm(instance=answer), "answer": answer})
            else:
                return HttpResponseRedirect(
                    reverse('discussions:question', kwargs={'question_id': "Q" + str(answer.QID.id)}))

discussions/templates/discussions/answer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PF</title>
</head>
<body>
<h3>{{ question.title }}</h3>
            <form method="post" action="{% url 'discussions:question' question.QID %}">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.name }}">{{ field.label }}:</label>
                    {{ field }}
                </div>
                {% endfor %}
                <button class="btn btn-primary btn-block" type="submit">Answer</button>
            </form>
</body>
</html>

discussions/templates/discussions/ask.html
{% extends "main/base.html" %}
{% load discussions_extras %}
{% block title %} Discussions
{% endblock %}
{% block body %}
{% include "main/nav.html" %}
<form method="post" action="{% if question %}{% url 'discussions:edit' 'Q'|addstr:question.id %} {% elif answer %}{% url 'discussions:edit' 'A'|addstr:answer.id %} {% else %}{% url 'discussions:index' %}{% endif %}">
                {% csrf_token %}
                {% for field in form %}
                    {% if not answer or field.name != 'title' %}
                        <div class="form-group">
                            <label for="{{ field.name }}">{{ field.label }}:</label>
                            {{ field }}
                        </div>
                    {% endif %}
                {% endfor %}
                <button class="btn btn-primary btn-block" type="submit">{% if question or answer %} Save {% else %}Ask a question{% endif %}</button>
            </form>
{% endblock %}

discussions/templates/discussions/delete.html
{% extends "main/base.html" %}
{% load discussions_extras %}
{% block title %} Discussions
{% endblock %}
{% block body %}
{% include "main/nav.html" %}
    <div class="container">
    <br><h4>Confirm deletion:</h4><hr><br>
        {% if question %}
            <div class="card">
                <div class="card-block">
                    <h5>Are you sure you want to delete your question <a href="{% url 'discussions:question' 'Q'|addstr:question.id %}">{{ question.title }}</a> </h5>
                    <br><br>
                    <div class="text-left">
                        <a href="{% url 'discussions:confirm' 'Q'|addstr:question.id %}"><button class="btn btn-success">Yes, I'am</button> </a>
                        <a href="{% url 'discussions:question' 'Q'|addstr:question.id %}"><button class="btn btn-danger">No, take me back</button> </a>
                    </div>
                </div>
            </div>
        {% elif answer %}
            <div class="card">
                <div class="card-block">
                    <h5>Are you sure you want to delete your answer to the question <a href="{% url 'discussions:question' 'Q'|addstr:answer.QID.id %}">{{ answer.QID.title }}</a> </h5>
                    <br><br>
                    <div class="text-left">
                        <a href="{% url 'discussions:confirm' 'A'|addstr:answer.id %}"><button class="btn btn-success">Yes, I'am</button> </a>
                        <a href="{% url 'discussions:question' 'Q'|addstr:answer.QID.id %}"><button class="btn btn-danger">No, take me back</button> </a>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

discussions/templates/discussions/discussion.html
{% extends "main/base.html" %}
{% load discussions_extras %}
{% block title %} Discussions
{% endblock %}
{% block body %}
{% include "main/nav.html" %}
    <br><br><div class="container">
        <div class="row">
            <div class="col-lg-7">
                <h3>Discussions:</h3><hr>
                    <div class="col-12">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                  <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#top" role="tab" aria-controls="top">Popular</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#recent" role="tab" aria-controls="profile">Recent</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#unanswered" role="tab" aria-controls="unanswered">Answers</a>
                  </li>
                </ul>

                <div class="tab-content">
                    <div class="tab-pane active" id="top" role="tabpanel"><br>
                        <div class="overflow">
                            <ul class="list-group">
                                {% for question in questions|dictsortreversed:"votes" %}
                                     <li class="list-group-item justify-content-between" data-toggle="tooltip" data-placement="top" title="asked by {{ question.username }} on {{ question.date }} has {{ question.count }} answers">
                                        <a href=" {% url 'discussions:question' 'Q'|addstr:question.id %}" style="color: black"><h5>{{ question.title }}</h5></a>
                                        <span class="badge badge-default badge-pill bg-{% if question.votes >= 0 %}success{% else %}danger{% endif %}">{{ question.votes }}</span>
                                     </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="tab-pane" id="recent" role="tabpanel"><br>
                        <div class="overflow">
                            <ul class="list-group">
                                {% for question in questions|dictsortreversed:"date" %}
                                     <li class="list-group-item justify-content-between" data-toggle="tooltip" data-placement="top" title="asked by {{ question.username }} on {{ question.date }} has {{ question.count }} answers">
                                        <a href="{% url 'discussions:question' 'Q'|addstr:question.id %}" style="color: black"><h5>{{ question.title }}</h5></a>
                                        <span class="badge badge-default badge-pill bg-{% if question.votes >= 0 %}success{% else %}danger{% endif %}">{{ question.votes }}</span>
                                     </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                  <div class="tab-pane" id="unanswered" role="tabpanel"><br>
                      <div class="overflow">
                            <ul class="list-group">
                                {% for question in questions|dictsort:"count" %}
                                         <li class="list-group-item justify-content-between" data-toggle="tooltip" data-placement="top" title="asked by {{ question.username }} on {{ question.date }} has {{ question.count }} answers">
                                            <a href="{% url 'discussions:question' 'Q'|addstr:question.id %}" style="color: black"><h5>{{ question.title }}</h5></a>
                                            <span class="badge badge-default badge-pill bg-{% if question.votes >= 0 %}success{% else %}danger{% endif %}">{{ question.votes }}</span>
                                         </li>
                                {% endfor %}
                            </ul>
                        </div>
                  </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 offset-1">
            <h3>Recent Activity:</h3><hr>
            {% for activity in activities %}
                {% if activity.on_username %}
                    {% if activity.AID %}
                        {% if activity.vote == True %}
                            <a href="{% url 'main:profile' activity.by_username.username %}">@{{ activity.by_username.username }}</a> upvoted <a href="{% url 'main:profile' activity.on_username.username %}">@{{ activity.on_username.username }}</a>'s answer to question <a href="{% url 'discussions:question' 'Q'|addstr:activity.AID.QID.id %}"> {{ activity.AID.QID.title }}</a><hr>
                        {% else %}
                            <a href="{% url 'main:profile' activity.by_username.username %}">@{{ activity.by_username.username }}</a> downvoted <a href="{% url 'main:profile' activity.on_username.username %}">@{{ activity.on_username.username }}</a>'s answer to question <a href="{% url 'discussions:question' 'Q'|addstr:activity.AID.QID.id %}"> {{ activity.AID.QID.title }}</a><hr>
                        {% endif %}
                    {% else %}
                        {% if activity.vote == True %}
                            <a href="{% url 'main:profile' activity.by_username.username %}">@{{ activity.by_username.username }}</a> upvoted <a href="{% url 'main:profile' activity.on_username.username %}">@{{ activity.on_username.username }}</a>'s question <a href="{% url 'discussions:question' 'Q'|addstr:activity.QID.id %}"> {{ activity.QID.title }}</a><hr>
                        {% else %}
                            <a href="{% url 'main:profile' activity.by_username.username %}">@{{ activity.by_username.username }}</a> downvoted <a href="{% url 'main:profile' activity.on_username.username %}">@{{ activity.on_username.username }}</a>'s question <a href="{% url 'discussions:question' 'Q'|addstr:activity.QID.id %}"> {{ activity.QID.title }}</a><hr>
                        {% endif %}
                    {% endif %}
                {% else %}
                    {% if activity.AID %}
                        <a href="{% url 'main:profile' activity.by_username.username %}">@{{ activity.by_username.username }}</a> answered<a href="{% url 'discussions:question' 'Q'|addstr:activity.AID.QID.id %}"> {{ activity.AID.QID.title }}</a><hr>
                    {% else %}
                            <a href="{% url 'main:profile' activity.by_username.username %}">@{{ activity.by_username.username }}</a> asked <a href="{% url 'discussions:question' 'Q'|addstr:activity.QID.id  %}">{{ activity.QID.title }}</a><hr>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </div>
        </div>
    </div>
{% endblock %}