discussions/urls.py
from django.conf.urls import url

from . import views

app_name = 'discussions'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>Q[0-9]+)$', views.question, name='question'),
    url(r'^ask/', views.ask, name='ask'),
    url(r'^answer/(?P<question_id>Q[0-9]+)$', views.answer, name='answer'),
    url(r'^delete/(?P<id>[AQ][0-9]+)', views.delete, name='delete'),
    url(r'^edit/(?P<id>[AQ][0-9]+)', views.edit, name='edit'),
    url(r'^confirm/(?P<id>[AQ][0-9]+)', views.confirm, name='confirm'),
    url(r'^vote/', views.vote, name='vote'),
]

main/urls.py
from django.conf.urls import url

from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/', views.login_view, name='login'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^search/', views.search, name='search'),
    url(r'^about/', views.about, name='about'),
    url(r'^leaderboard/', views.LeaderBoard, name='leaderboard'),
    url(r'^activity/', views.activity_all, name='activity_all'),
    url('^profile/(?P<username>[a-zA-Z0-9_]+)', views.profile, name='profile'),
    url('^activity/(?P<username>[a-zA-Z0-9_]+)', views.activity, name='activity'),
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    url(r'^posts/', views.posts, name='posts'),
    url(r'^post/(?P<id>P[0-9]+)', views.post, name='post'),

]

pf/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^',include('main.urls')),
    url(r'^discussions/',include('discussions.urls')),
    url(r'^admin/', admin.site.urls),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from discussions.models import Question, Answer
from datetime import datetime


# Create your models here.


class Profile(models.Model):
    username = models.ForeignKey(User, on_delete=None, primary_key=True)
    image = models.CharField(max_length=255, default="")
    points = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    hacker_earth_username = models.CharField(max_length=255, default="", blank=True)
    spoj_username = models.CharField(max_length=255, default="", blank=True)
    codechef_username = models.CharField(max_length=255, default="", blank=True)
    hacker_earth_rating = models.IntegerField(default=0)
    spoj_rating = models.IntegerField(default=0)
    codechef_rating = models.IntegerField(default=0)
    total_questions = models.IntegerField(default=0)


    def __str__(self):
        return self.username.username

class View(models.Model):
    ip = models.CharField(max_length=30, default="")
    time = models.DateTimeField(default=datetime.now)
    user = models.ForeignKey(User, on_delete=None)

    def __str__(self):
        return self.user.username + " " + self.ip


class Activity(models.Model):
    by_username = models.ForeignKey(User, on_delete=None, related_name='by')
    QID = models.ForeignKey(Question, on_delete=None, null=True, blank=True)
    AID = models.ForeignKey(Answer, on_delete=None, null=True, blank=True)
    vote = models.BooleanField(default=True, blank=True)
    type = models.BooleanField(default=False)
    on_username = models.ForeignKey(User, on_delete=None, null=True, blank=True, related_name='on')
    datetime = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return str(self.datetime) + " by " + self.by_username.username

    class Meta:
        verbose_name_plural = 'Activities'
        ordering = ['-datetime']


class Post(models.Model):
    username = models.ForeignKey(User, on_delete=None)
    title = models.CharField(max_length=500, default="")
    description = models.TextField(max_length=5000, default="")
    datetime = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.title + " " + self.username.username

    class Meta:
        ordering = ['-datetime']

main/views.py
import requests
import re
from bs4 import BeautifulSoup
from .form import Loginform, Signupform
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, Http404
from django.http import HttpResponse, JsonResponse
from .models import Profile, Activity, View, Post
from discussions.models import Question
from django.db.models import Q, Case, When, Sum
from django import forms
from datetime import datetime
import datetime

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            if request.method == "GET":
                if request.GET["next"]:
                    return HttpResponseRedirect(request.GET['next'])
            return HttpResponseRedirect(reverse('main:profile', kwargs={'username': user.username}))
    return render(request, 'main/login.html', {"form": Loginform(request.POST or None)})

"""def init_crawl_codechef(x):
    url = "https://www.codechef.com/recent/user?page=0&user_handle=" + x + "&_=1510300136417"
    # mathecodician
    # sagar_sam
    # print(url)
    pages = []
    r = requests.get(url)
    today = datetime.date.today()
    soup = BeautifulSoup(r.content, "html.parser")
    output2 = " "
    for j in soup.text[12:]:
        if j != ",":
            output2 += j
        else:
            break

    output2 = int(output2)
    # print(output2)
    count = 0
    accepted = 0
    count2 = 0
    stop = 0
    num_of_pages = 0
    for a in range(0, output2):
        # for a in range(0, 10):
        url = "https://www.codechef.com/recent/user?page=" + str(a) + "&user_handle=" + x + "&_=1510300136417"
        pages.append(url)

    for i in pages:
        count += 1

    for item in pages:
        num_of_pages += 1
        r = requests.get(item)
        soup = BeautifulSoup(r.content, "html.parser")
        g_data3 = soup.find_all("td")
        count = 0
        for item3 in g_data3:
            if (count % 4 == 0):
                output = " "
                output = item3.contents[0]
                wordList = re.sub("[^\w]", " ", output).split()
                if wordList.__len__() > 2:
                    streee = wordList[2]
                    if streee == 'ago':
                        case = today
                        case = case.replace(case.year - 2000)
                        case = case.strftime('%d\/%m\/%Y')
                        output = "12:12 PM " + case + "<\/td>"

            elif count % 2 == 0:
                flag = 0
                points = []
                for j in item3.contents[0]:
                    flag += 1
                if (flag == 6):
                    counter = 0
                    for j in item3.contents[0]:
                        counter += 1
                        if (counter == 3):
                            points.append(str(j))
                if (points == ['100']):
                    accepted += 1
                    x = output
                    x = int(output[9:11])
                    y = int(output[13:15])
                    z = 2000
                    z = z + int(output[17:19])
                    someday = datetime.date(z, y, x)  # .strftime('%Y-%m-%d')
                    some2 = datetime.date(z, y, x).strftime('%Y-%m-%d')
                    pastday = today - datetime.timedelta(days=11)
                    past = pastday.strftime('%Y-%m-%d')
                    if (some2 > past):
                        count2 += 1
                    else:
                        flag = 1
                    output = " "
            count += 1
            if (stop == 1):
                break
        if (stop == 1):
            break
    output = int(count2)
    init_codechef_rating = output
    return init_codechef_rating"""

def init_crawl_spoj(input):
    pages = []
    count = 0
    count2 = 0
    output = " "
    stop = 0
    flag5 = 1
    today = datetime.date.today()
    url5 = 'http://www.spoj.com/users/' + input
    r5 = requests.get(url5)
    soup5 = BeautifulSoup(r5.content, "html.parser")
    x5 = soup5.find("div", {"class": "col-md-3"})
    if x5 is None:
        flag5 = 0

    if flag5 is 1:
        for a in range(0, 5):
            url = 'http://www.spoj.com/status/' + input + '/all/start=' + str(a * 20)
            pages.append(url)
        for item in pages:
            page = requests.get(item)
            soup = BeautifulSoup(page.content, "html.parser")
            artist_name_list = soup.find_all("tr", {"class": "kol1"})
            artist_name_list2 = soup.find_all("tr", {"class": "kol2"})
            artist_name_list3 = soup.find_all("tr", {"class": "kol3"})
            for i in artist_name_list:
                # print(i.contents[3].text)
                count += 1
                for j in i.contents[3].text:
                    if j != " ":
                        output += j
                    else:
                        output = output.strip()
                        # print(output)
                        x = int(output[:4])
                        y = int(output[5:7])
                        z = int(output[8:10])
                        someday = datetime.date(x, y, z)  # .strftime('%Y-%m-%d')
                        some2 = datetime.date(x, y, z).strftime('%Y-%m-%d')
                        pastday = today - datetime.timedelta(days=30)
                        past = pastday.strftime('%Y-%m-%d')
                        if (some2 > past):
                            count2 += 1
                        else:
                            stop = 1
                        output = " "
                        break
                if (stop == 1):
                    break
            for i in artist_name_list2:
                # print(i.contents[3].text)
                count += 1
                for j in i.contents[3].text:
                    if j != " ":
                        output += j
                    else:
                        output = output.strip()
                        # print(output)
                        x = int(output[:4])
                        y = int(output[5:7])
                        z = int(output[8:10])
                        someday = datetime.date(x, y, z)  # .strftime('%Y-%m-%d')
                        some2 = datetime.date(x, y, z).strftime('%Y-%m-%d')
                        pastday = today - datetime.timedelta(days=10)
                        past = pastday.strftime('%Y-%m-%d')
                        if (some2 > past):
                            count2 += 1
                        else:
                            stop = 1
                        output = " "
                        break
                if (stop == 1):
                    break
            for i in artist_name_list3:
                # print(i.contents[3].text)
                count += 1
                for j in i.contents[3].text:
                    if j != " ":
                        output += j
                    else:
                        output = output.strip()
                        # print(output)
                        x = int(output[:4])
                        y = int(output[5:7])
                        z = int(output[8:10])
                        someday = datetime.date(x, y, z)  # .strftime('%Y-%m-%d')
                        some2 = datetime.date(x, y, z).strftime('%Y-%m-%d')
                        pastday = today - datetime.timedelta(days=10)
                        past = pastday.strftime('%Y-%m-%d')
                        if (some2 > past):
                            count2 += 1
                        else:
                            stop = 1
                        output = " "
                        break
                if (stop == 1):
                    break
            if (stop == 1):
                break
    output = int(count2)
    init_spoj_rating = output
    return init_spoj_rating


def signup(request):
    if request.method == "POST":
        form = Signupform(request.POST)
        if form.is_valid():
            user = User.objects.create_user(request.POST['username'], request.POST['email'], request.POST['password'])
            user.first_name = request.POST['first_name']
            user.last_name = request.POST['last_name']
            user.save()
            profile = Profile.objects.create(username=user, image="nullasofnow")
            profile.hacker_earth_username = request.POST['hacker_earth_username']
            profile.spoj_username = request.POST['spoj_username']
            profile.codechef_username = request.POST['codechef_username']
            profile.save()
            #profile.codechef_rating = init_crawl_codechef(profile.codechef_username)
            profile.spoj_rating = init_crawl_spoj(profile.spoj_username)
            #profile.hacker_earth = init_crawl_hackerearth(profile.hacker_earth_rating)
            profile.save()
            login(request, user)
            return redirect('main:profile', username=user.username)
    return render(request, 'main/signup.html', {"form": Signupform(request.POST or None)})

def LeaderBoard(request):

    profiles = Profile.objects.all()
    for profile in profiles:
        try:
            total = int(profile.codechef_rating + profile.spoj_rating + profile.hacker_earth_rating)
            profile.total_questions = total
            profile.save()
        except ValueError:
            pass

    return render(request, 'main/leaderboard.html', {"profiles": Profile.objects.all()})

main/templates/main/home.html
{% extends "main/base.html" %}
{% load static %}
{% load humanize %}
{% load discussions_extras %}
{% block title %}PF | Home{% endblock %}
{% block body %}
    <div class="row text-center">
        <div class="col-10 offset-1">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" style="width:100%;height:35%"
                             src="{% static 'main/images/download.svg' %}" alt="First slide">

                        <div class="carousel-caption d-none d-md-block">
                            <h3>First slide</h3>

                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis deserunt ea eaque eius
                                eos esse
                                incidunt iste modi molestias mollitia nemo nihil pariatur porro repellendus sed soluta,
                                temporibus
                                vitae voluptatem?</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" style="width:100%;height:35%"
                             src="{% static 'main/images/download (1).svg' %}" alt="Second slide">

                        <div class="carousel-caption d-none d-md-block">
                            <h3>Second slide</h3>

                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis deserunt ea eaque eius
                                eos esse
                                incidunt iste modi molestias mollitia nemo nihil pariatur porro repellendus sed soluta,
                                temporibus
                                vitae voluptatem?</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" style="width:100%;height:35%"
                             src="{% static 'main/images/download (2).svg' %}" alt="Third slide">

                        <div class="carousel-caption d-none d-md-block">
                            <h3>Second slide</h3>

                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis deserunt ea eaque eius
                                eos esse
                                incidunt iste modi molestias mollitia nemo nihil pariatur porro repellendus sed soluta,
                                temporibus
                                vitae voluptatem?</p>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div><br><br>

    <div class="row">
        <div class="col-lg-6 offset-1">
            <div class="card">
                <h3 class="card-header">
                    Posts
                </h3>

                <div class="card-block">
                    <div class="list-group">
                        {% for post in posts %}
                            <a href="{% url 'main:post' 'P'|addstr:post.id %}"
                               class="list-group-item list-group-item-action flex-column align-items-start">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">{{ post.title|title }}</h5>
                                    <small>{{ post.datetime|naturaltime }}</small>
                                </div>
                                <p class="mb-1">{{ post.description|truncatechars:40 }}</p>
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <br>

        <div class="col-lg-3 offset-1">
            <div class="card">
                <h3 class="card-header">
                    Top programmers
                </h3>

                <div class="card-block">
                    <ul class="list-group" style="width: 100%;">
                        <div class="row">
                            {% for user in users %}
                                <a style="width: 100%" href="{% url 'main:profile' user.username %}">
                                    <li class="list-group-item">
                                        <div class="col-lg-10">@{{ user.username }}
                                        <span class="checkmark">
                                            <div class="checkmark_stem"></div>
                                            <div class="checkmark_kick"></div>
                                        </span>
                                        </div>
                                        <div class="col-lg-2"><span
                                                class="badge badge-default badge-pill">{{ user.profile_set.all.0.points }}</span>
                                        </div>
                                    </li>
                                </a>
                            {% endfor %}
                        </div>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-1"></div>
    </div><br><br>

    <div class="row">
        <div class="col-10 offset-1">
            <h3>Discussions</h3><br>
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#top" role="tab" aria-controls="top">Top</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#recent" role="tab" aria-controls="profile">Recent</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#unanswered" role="tab" aria-controls="unanswered">Unanswered</a>
                </li>
            </ul>

            <div class="tab-content">
                <div class="tab-content">
                    <div class="tab-pane active" id="top" role="tabpanel"><br>

                        <div class="overflow" style="height: 30vh;">
                            <ul class="list-group">
                                {% for question in questions|dictsortreversed:"votes" %}
                                    <li class="list-group-item justify-content-between" data-toggle="tooltip"
                                        data-placement="top"
                                        title="asked by {{ question.username }} on {{ question.date }} has {{ question.count }} answers">
                                        <a href=" {% url 'discussions:question' 'Q'|addstr:question.id %}"
                                           style="color: black"><h5>{{ question.title }}</h5></a>
                                        <span class="badge badge-default badge-pill bg-{% if question.votes >= 0 %}success{% else %}danger{% endif %}">{{ question.votes }}</span>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="tab-pane" id="recent" role="tabpanel"><br>

                        <div class="overflow" style="height: 30vh;">
                            <ul class="list-group">
                                {% for question in questions|dictsortreversed:"date" %}
                                    <li class="list-group-item justify-content-between" data-toggle="tooltip"
                                        data-placement="top"
                                        title="asked by {{ question.username }} on {{ question.date }} has {{ question.count }} answers">
                                        <a href="{% url 'discussions:question' 'Q'|addstr:question.id %}"
                                           style="color: black"><h5>{{ question.title }}</h5></a>
                                        <span class="badge badge-default badge-pill bg-{% if question.votes >= 0 %}success{% else %}danger{% endif %}">{{ question.votes }}</span>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="tab-pane" id="unanswered" role="tabpanel"><br>

                        <div class="overflow" style="height: 30vh;">
                            <ul class="list-group">
                                {% for question in questions|dictsort:"count" %}
                                    <li class="list-group-item justify-content-between" data-toggle="tooltip"
                                        data-placement="top"
                                        title="asked by {{ question.username }} on {{ question.date }} has {{ question.count }} answers">
                                        <a href="{% url 'discussions:question' 'Q'|addstr:question.id %}"
                                           style="color: black"><h5>{{ question.title }}</h5></a>
                                        <span class="badge badge-default badge-pill bg-{% if question.votes >= 0 %}success{% else %}danger{% endif %}">{{ question.votes }}</span>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/login.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}Login{% endblock %}
{% block body %}<br>
    <div class="row justify-content-center">
        <div class="col-6">
           <div class="card">
              <h3 class="card-header">Login</h3>
              <div class="card-block">
                <form method="post" action="">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group" id="login_{{ field.name }}">
                    <label for="{{ field.name }}">{{ field.label }}:</label>
                    {{ field }}
                    <div class="form-control-feedback" id="feedback_{{ field.name }}"></div>
                </div>
                {% endfor %}
                <div class="col text-center">
                <button class="btn btn-primary text-center" type="submit">Login</button>
                </div>
                </form>
                  <small>Don't have an account? <a href="{% url 'main:signup' %}">Sign up here</a></small>
              </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/nav.html
{% url 'main:index' as home %}
{% url 'main:posts' as posts %}
{% url 'main:about' as about %}
{% url 'main:login' as login %}
{% url 'main:signup' as signup %}
{% url 'main:profile' request.user.username as profile %}
{% url 'discussions:index' as discussions %}
{% url 'discussions:question' as question %}
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-brand">Programmers Forum</div>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.get_full_path == home %}active{% endif %}">
                <a class="nav-link" href="{% url 'main:index' %}">Home</a>
            </li>
            <li class="nav-item {% if request.get_full_path == posts %}active{% endif %}">
                <a class="nav-link" href="{% url 'main:posts' %}">Posts</a>
            </li>
            <li class="nav-item {% if discussions in request.get_full_path %}active{% endif %}">
                <a class="nav-link" href="{% url 'discussions:index' %}">Discussions</a>
            </li>
            <li class="nav-item {% if request.get_full_path == about %}active{% endif %}">
                <a class="nav-link" href="{% url 'main:about' %}">About</a>
            </li>
            <li class="nav-item {% if request.get_full_path == leaderboard %}active{% endif %}">
                <a class="nav-link" href="{% url 'main:leaderboard' %}">LeaderBoard</a>
            </li>
            &nbsp;&nbsp;
            <form class="form-inline my-2 my-lg-0" action="{% url 'main:search' %}" method="get">
                <input class="form-control mr-sm-2" type="text" name="q" placeholder="Search">
                <button class="btn btn-btn-secondary  my-2 my-sm-0" type="submit">Search</button>
            </form>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if not user.is_authenticated %}
                <li class="nav-item {% if request.get_full_path == login %}active{% endif %}">
                    <a class="nav-link" href="{% url 'main:login' %}">Log In</a>
                </li>
                <li class="nav-item {% if request.get_full_path == signup %}active{% endif %}">
                    <a class="nav-link" href="{% url 'main:signup' %}">Sign Up</a>
                </li>
                {% else %}
                {% if discussions in request.get_full_path %}
                <li class="nav-item {% if 'discussions/ask' in request.get_full_path %}active {% endif %}">
                    <a href="{% url 'discussions:ask' %}" class="nav-link">Ask Question</a>
                </li>&nbsp;&nbsp;{% endif %}
                <li class="nav-item dropdown {% if request.get_full_path == profile %}active{% endif %}">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        {{ user.username }} ({{ request.user.profile_set.all.0.points }})
                    </a>

                    <div class="dropdown-menu" style=" right: 0;left: auto;" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'main:profile' request.user.username %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'main:activity' request.user.username %}">Activity</a>
                        <a class="dropdown-item" href="{% url 'main:logout' %}">Logout</a>
                    </div>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

main/templates/main/post.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}Sign in{% endblock %}
{% block body %}
    <div class="container">
    <h3>Posts by admins</h3><hr>
            <div class="row">
                <div class="col-10 offset-1">
                   <div class="card">
                      <h3 class="card-header">{{ post.title }} <small>&nbsp;by <a href="{% url 'main:profile' post.username %}">@{{ post.username }}</a> </small></h3>
                      <div class="card-block">
                        {{ post.description|linebreaks }}
                        <div class="col text-right">
                              on <small style="font-size: medium" >{{ post.datetime }}</small>&nbsp;
                        </div>
                      </div>
                   </div>
                </div>
            </div>
    </div>
{% endblock %}

main/templates/main/posts.html
{% extends "main/base.html" %}
{% load discussions_extras %}
{% load static %}
{% block title %}Sign in{% endblock %}
{% block body %}
    <div class="container">
    <h3>Posts by admins</h3><hr>
        {% for post in posts %}<br>
            <div class="row">
                <div class="col-10 offset-1">
                   <div class="card">
                      <h3 class="card-header">{{ post.title }} <small>&nbsp;by <a href="{% url 'main:profile' post.username %}">@{{ post.username }}</a> </small></h3>
                      <div class="card-block">
                        {{ post.description|truncatewords:35 }}
                          <div class="col text-right">
                              on <small style="font-size: medium" >{{ post.datetime }}</small>&nbsp;
                            </div>
                      </div>
                   </div>
                    <div style="margin-top: 7px" class="col text-right">
                        <a href="{% url 'main:post' 'P'|addstr:post.id %}"><button class="btn btn-primary text-center" type="submit">View post</button></a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}